dist:
  module: github.com/lumigo-io/opentelemetry-collector-contrib
  name: lumigo-collector
  description: Lumigo OpenTelemetry collector
  otelcol_version: "0.85.0"
  version: "lumigo-dev"
  output_path: dist

exporters:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awskinesisexporter v0.85.0"
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.85.0
  - gomod: "go.opentelemetry.io/collector/exporter/otlphttpexporter v0.85.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.85.0"

extensions:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/headerssetterextension v0.85.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.85.0"

receivers:
  - gomod: "go.opentelemetry.io/collector/receiver/otlpreceiver v0.85.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8sobjectsreceiver v0.85.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/syslogreceiver v0.85.0"

processors:
  - gomod: "go.opentelemetry.io/collector/processor/batchprocessor v0.85.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.85.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.85.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.85.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.85.0"
